@startuml Enrollment
title Enrollment
participant "Pregnant Woman" as PW
participant "Clerk" as Clerk
participant "Nurse" as Nurse
participant "App" as App
participant "Engine" as Engine
participant "Server" as Server

Nurse -> App: Enrolls patient in ANC
App -> Engine: $apply ANC.S01
Engine -> App: Returns CarePlan
App -> Nurse: Displays CarePlan
Nurse -> App: Accept CarePlanOfRecord
App -> Nurse: Confirms Save

@enduml