library ANCCommonConfig version '0.1.0'

/*
  '1019AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' - Concept - COMPLETE BLOOD COUNT
  '165395AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' - Concept - Haemoglobin measured from haemoglobinometer (g/dl)
  '165396AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' - Concept - Haemoglobin measured from color scale (g/dl)
*/

define "Haemoglobin Test Type":
  '1019AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' //Complete Blood Count
